#cloud-config
package_update: true
package_upgrade: true
packages:
  - python3-pip
  - build-essential
  - unzip
  - jq
  - git
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - curl
  - wget
snap:
    commands:
      00: snap install yq
      01: snap install microk8s --classic --channel=1.27/stable
final_message: "The system is finally up, after $UPTIME seconds"
output: {all: '| tee -a /var/log/cloud-init-output.log'}