---
- name: 'Update all deployed systems'
  hosts: all
  tasks:
    - name: Update yum packages on RPM based systems 
      ansible.builtin.yum: 
        name=* 
        state=latest
      when: ansible_facts['os_family'] == "RedHat"    
    - name: Update apt packages
      ansible.builtin.apt: 
        upgrade=yes 
        update_cache=yes
      when: ansible_facts['os_family'] == "Debian"   